name: Test Workflow

on:
  workflow_dispatch: # allows manual run from the Actions tab

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "✅ GitHub Actions is working!"
